### ISSUE TITLE
Regression suggestions

### ISSUE THREAD

**Issue by brooksjessup** [dlab-berkeley/Python-Machine-Learning#10]
There is a quite a lot of time spent on preprocessing in this notebook. Would it be possible to streamline the preprocessing a bit and focus more on the regression models themselves? Perhaps the emphasis of the preprocessing section could be more on feature selection for the models rather than cleaning and transforming data?

The challenge at the end seems rather difficult and open-ended. I wonder whether learners are usually able to complete this quickly enough to go over together by the end of the workshop?

**Comment by pssachdeva** [comment]
Closed by #39.
