### ISSUE TITLE
Part 1: Classification

### ISSUE THREAD

**Issue by emgrabow9** [dlab-berkeley/Python-Machine-Learning#12]
1) I think we've already decided to replace the iris dataset, but I'll include it here as a reminder. With whatever dataset we are using, I would suggest putting the dataset into pandas dataframe form since that will be the most common form for people to work with.

2) Include a visualization of the decision tree, if possible.

3) I think there is some inconsistency in the definitions of specificity, precision, and recall between the notebook and the slides, but I'm having trouble remembering exactly what it is. 

4) For each of the ML models included I would suggest emphasizing the parameters that one is likely to tune using hyperparameter optimization

5) Instead of random forests, consider using the time to discuss another classification technique (such as SVM)

6) Include a more explicit discussion of cross-validation number of folds and how it plays into over/under-fitting

**Comment by stemlock** [comment]
I would also add to this list that if the workshop were to stick with using random forests for the second model, it would be useful to discuss how/why ensembled methods like random forest and boosting can offer improvements over a single decision tree learner. At present, these methods seem to be introduced with no reasoning.

**Comment by pssachdeva** [comment]
Closed by #42
