### ISSUE TITLE
Part 2: Regression

### ISSUE THREAD

**Issue by emgrabow9** [dlab-berkeley/Python-Machine-Learning#13]
1. Consider starting this section with an overview of the dataprocessing workflow, such as a flowchart or decision tree.
2. Consider including guidelines on choosing which type of regression to use.
3. Potentially we could emphasize the non-parametric / non-linear regression techniques, since I see these as the more likely cases in which people would turn to sklearn. 
4. I would also suggest introducing a little more scaffolding into the challenge exercises. (or potentially intersperse smaller challenge questions throughout a notebook). I find that going from passive reading/executing of the notebook to coding can be difficult sometimes. For example, break the challenge question down into steps, and include a bit of skeleton code for students to start from.

**Comment by pssachdeva** [comment]
Closed by #39.
