### ISSUE TITLE
Estimators vs Transformers

### ISSUE THREAD

**Issue by brooksjessup** [dlab-berkeley/Python-Machine-Learning#4]
A small terminology issue: The regression notebook seems to confuse "estimators" and "transformers". The notebook refers, for example, to SimpleImputer as an estimator but I think it should be classified as a transformer. My understanding is that estimators involve prediction, whereas transformers do not (i.e. preprocessing). Here's a stackoverflow discussion: https://stackoverflow.com/questions/54899647/what-is-the-difference-between-transformer-and-estimator-in-sklearn

**Comment by EastBayEv** [comment]
https://stackoverflow.com/questions/54899647/what-is-the-difference-between-transformer-and-estimator-in-sklearn
