### ISSUE TITLE
Slide deck suggestions

### ISSUE THREAD

**Issue by brooksjessup** [dlab-berkeley/Python-Machine-Learning#8]
How about a slide toward the beginning about what a "model" is (vs algorithm, for example) in machine learning?

The workshop mainly uses scikit-learn. Do we want to explain why we are using this library, and maybe just give a brief mention of the other big ml libraries like PyTorch and TensorFlow?

Do we want to say something in this intro about deep learning even if we aren't going to get there in the workshop?

Do we want to mention the trend toward AutoML, particularly because there is a notebook on this included at the end of the workshop?

**Comment by pssachdeva** [comment]
Closed by newest slide deck
