### ISSUE TITLE
Classification suggestions

### ISSUE THREAD

**Issue by brooksjessup** [dlab-berkeley/Python-Machine-Learning#9]
Most courses on ML teach regression before classification (including The Elements of Statistical Learning, which we recommend in the slide deck). Is there an advantage to reversing this and teaching classification first instead?

The most common algorithm for classification is logistic regression. Why don't we start with this here, before jumping to decision trees, etc.?

The explanation of each algorithm (how it works, what it's advantages and disadvantages are, when to use it) seems rather thin. Do we want to give a bit more of an introduction (and intuition) to the algorithms being taught?

**Comment by EastBayEv** [comment]
How to best present machine learning on data? Continuous/regression ("statistics approach") first, then classification/discrete ("computer science approach") or vice-versa?

**Comment by pssachdeva** [comment]
Closed by #39.
